### ISSUE TITLE
Create custom metrics

### ISSUE THREAD

**Issue by MarkEdmondson1234** [8-bit-sheep/googleAnalyticsR#325]
**Is your feature request related to a problem? Please describe.**
Support making custom metrics https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/customMetrics/insert

**Describe the solution you'd like**
Custom metrics can be queried dynamically but not created like custom dimensions can

**Comment by gronerik** [comment]
UA is now gone (sniff), closing this. If this needs to be implemented for GA4 let's open a new feature request issue for it.
