### ISSUE TITLE
GAv3 multi-support batching doesn't work anymore

### ISSUE THREAD

**Issue by MarkEdmondson1234** [8-bit-sheep/googleAnalyticsR#347]
Will remove support for multi-support batching for v3 API.

This test failing:

```r
  multi <- google_analytics_3(c(ga_id, ga_id2),
                              start = "2015-07-31", end = "2015-10-01",
                              dimensions=c('medium'),
                              metrics = c('sessions'),
                              sort = "ga:sessions")
```

The responses from the GAv3 API no longer include "content-length" which is specified as necessary in the docs: https://developers.google.com/analytics/devguides/reporting/core/v3/batching

Tried to log it here: https://github.com/MarkEdmondson1234/googleAuthR/commit/87ee376e0bfbac31e418e78915e78691275322d6

**Comment by MarkEdmondson1234** [comment]
For this and as GA4 is now out, its time to deprecate this function.  The only sticking point is the multi-channel reports, so some way to keep those perhaps if required.

**Comment by nviraj** [comment]
Hello,

I am facing the following issue when I use google_analytics_3 function with WALK samplingLevel. Not sure if this is the same issue.
`Error in x[[1]] : subscript out of bounds`

Unfortunately not able to V4 APIs due to reasons out of control.
This happens for durations as small as a month. Using 0.8 currently.

Here is the traceback. Please let me know if you need ay additional info.

```
> traceback()
7: FUN(X[[i]], ...)
6: lapply(bl, function(x) {
       if (!inherits(x[[1]], "data.frame")) {
           stop("Attempting to rbind a non dataframe output. \n                                       Set data_frame_output to FALSE?")
       }
       else Reduce(rbind, x)
   })
5: Reduce(rbind, lapply(bl, function(x) {
       if (!inherits(x[[1]], "data.frame")) {
           stop("Attempting to rbind a non dataframe output. \n                                       Set data_frame_output to FALSE?")
       }
       else Reduce(rbind, x)
   }))
4: googleAuthR::gar_batch_walk(ga, dates, gar_pars = ga_pars, pars_walk = c("start-date", 
       "end-date"), batch_function = bf)
3: walkData(ga, ga_pars, ga_pars$`start-date`, ga_pars$end)
2: loop_ids(id = id, ga_pars = ga_pars, samplingLevel = samplingLevel, 
       max_results = max_results, ga = ga)
1: google_analytics_3(view_id, start = "2020-01-01", end = "2020-01-30", 
       metrics = metrics_needed, dimensions = dimensions_needed, 
       samplingLevel = "WALK")
```

Thanks!

**Comment by MarkEdmondson1234** [comment]
What version are you using?  `sessionInfo()`

**Comment by MarkEdmondson1234** [comment]
And why can't you use v4?  It would return the same data?

**Comment by nviraj** [comment]
Thanks for your quick response @MarkEdmondson1234. I had an incorrect assumption about the V4 API. Switched to it and works like a charm. Apologies!

**Comment by gronerik** [comment]
UA is now gone (sniff), closing this.
