### ISSUE TITLE
Data upload with no filename

### ISSUE THREAD

**Issue by MarkEdmondson1234** [8-bit-sheep/googleAnalyticsR#40]
Apparently its an error with client libraries so why does it happen here too?

http://stackoverflow.com/questions/39537395/file-name-in-uploaddata-google-analytics

**Comment by joseramoncajide** [comment]
Hi Mark.
I just solved this by uploading files using Curl. The filename need to be specified in Json format. Do you need help?

**Comment by MarkEdmondson1234** [comment]
Help appreciated, have you an example? The function is here https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/R/custom_data_source.R#L229

**Comment by joseramoncajide** [comment]
The trick is in the metadata var.
```
library('jsonlite')
metadata <- tempfile()
writeLines(jsonlite::toJSON(list(title = unbox("ga_uploads/refunds.csv"))), metadata)

data <- POST(gaEndPoint, 
             body = list(
               metadata = upload_file(metadata, type = "application/json; charset=UTF-8"), 
               media = upload_file('ga_uploads/refunds.csv', "application/octet-stream")
             ), 
             add_headers("Content-Type" = "multipart/related"),
             config(token = token), 
             encode = "multipart", 
             verbose())

stop_for_status(data)
```

**Comment by MarkEdmondson1234** [comment]
I need to test this, but should be fixed.

**Comment by byapparov** [comment]
Hi Mark,

Should I expect upload function to work. I get 400 on both data.frame and file path.

Thanks
Bulat
