### ISSUE TITLE
ga_unsampled_list() and ga_unsampled_download() unable to get reports

### ISSUE THREAD

**Issue by a-jakob** [8-bit-sheep/googleAnalyticsR#430]
## What goes wrong
Since 10.08.2023 the reports don't appear on ga_unsampled_list() anymore and can't be dowloaded through ga_unsampled_download()

## Steps to reproduce the problem
Having unsampled reports scheduled, `ga_unsampled_list(accountId = myAccount,webPropertyId = myWebProperty,profileId = myProfileId)` 

## Expected output
New reports appear again on the list and can be downloaded

## Actual output
"Error: Report title not found. Please enter a valid title. 
           Remember it is case-sensitive" (although the report exists)
Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

## 'API Data failed to parse' diagnostics

If you have an error starting with:

`API Data failed to parse.`

* Please install googleAuthR >v0.7.9000:

```r
remotes::install_github("MarkEdmondson1234/googleAuthR")
```

* Restart the R session and run your bugged code.
* It should write a file called `gar_parse_error.rds` to your working directory.
* Run the below to output some diagnostic information and paste the response here.

```r
googleAuthR::gar_debug_parsing("gar_parse_error.rds")
```

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed
googleAuthR_2.0.1 googleAnalyticsR_1.1.0

**Comment by MarkEdmondson1234** [comment]
Is this API active anymore anywhere? Can you call it via the online api explorer?

**Comment by a-jakob** [comment]
The reports are available on online version--Diese Nachricht wurde von meinem Android Mobiltelefon mit mail.com Mail gesendet.On 8/14/23, 11:25 Mark ***@***.***> wrote:

   
  Is this API active anymore anywhere? Can you call it via the online api explorer?

**Comment by MarkEdmondson1234** [comment]
To be clear, available via API calls or via webUI? Can you link to a successful API call?

**Comment by a-jakob** [comment]
they're available via GA-webUI, but not via API, I can link successfully to the API and get older reports (for example daily reports before 10.08).

**Comment by MarkEdmondson1234** [comment]
It sounds like it's been turned off. Maybe someone else can confirm, I haven't any UA360 properties to test it with.

**Comment by a-jakob** [comment]
Ok, that sounds bad... but first of all thank you very much for your support and for the packet-administration. Would you have an idea of how automate the unsampled reports downloads otherwise?
If it's helpful to diagnose and you have the time and interest, I could arrange a call. Just write me at andre.jakob@transfermarkt.de if it's the case.

**Comment by a-jakob** [comment]
Another little piece of information: when I request a new unsampled report it appears on api as "pending". When it's complete, it doesn't appear anymore.

**Comment by MarkEdmondson1234** [comment]
If it's GA360 I suggest trying to replicate the report in BigQuery

**Comment by a-jakob** [comment]
For the records, if somebody has the same problem:
- GA-Reports aren't available on GA-API anymore, but they're still being delivery on GDrive
- I installed `googledrive` package and followed the instructions available on https://gargle.r-lib.org/articles/non-interactive-auth.html
- Having the reports' names they can be downloaded automatically from a shiny server just as before.

Thanks Mark for trying to help!

**Comment by gronerik** [comment]
Legacy UA stuff, not available anymore by Google.
